apiVersion: quickube.com/v1alpha1
kind: QWorker
metadata:
  labels:
    app.kubernetes.io/name: qworker
  name: qworker-example
spec:
  podSpec:
    serviceAccountName: qscaler-worker
    containers:
      - name: pyworker
        image: localhost:5001/worker:0.0.1
        env:
          - name: QWORKER_NAME
            value: "qworker-example"
  scaleConfig:
    queue: "queue1"
    minReplicas: 2
    maxReplicas: 20
    scalerConfigRef: redis-config
    scalingFactor: 1