apiVersion: quickube.com/v1alpha1
kind: QWorker
metadata:
  labels:
    app.kubernetes.io/name: qworker
  name: qworker-example
spec:
  podSpec:
    serviceAccountName: qscaler-worker
    containers:
      - name: pyworker
        image: localhost:5001/worker:latest
        imagePullPolicy: Always
  scaleConfig:
    activateVPA: true
    queue: "queue1"
    minReplicas: 1
    maxReplicas: 5
    scalerConfigRef: redis-config
    scalingFactor: 1