apiVersion: quickube.com/v1alpha1
kind: QWorker
metadata:
  labels:
    app.kubernetes.io/name: qworker
    app.kubernetes.io/managed-by: kustomize
  name: qworker-example
spec:
  podSpec:
    containers:
      - name: pyworker
        image: localhost:5001/worker:0.0.1
  scaleConfig:
    queue: "queue1"
    minReplicas: 4
    maxReplicas: 20
    scalerConfigRef: redis-config
    scalingFactor: 1