name: Release Workflow

on:
  release:
    types:
      - published
      - edited

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          build_format: "wheel"
          poetry_install_options: "--without lint --without test"
