name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: python
          package-name: gamba
          version-file: pyproject.toml
          token: ${{ secrets.GIT_TOKEN }}